### PR TITLE
Remove skyscanner role

### PR DESCRIPTION
**Pull request by kelliedesigner**
Please make sure all of these are checked before submitting a new pull request.

- [x] A job is part of design system teams or its main focus will be on building and maintaining design system(s).
- [x] I've added the job position at the top of specific category.
- [x] I've read [CONTRIBUTING.md](/contributing.md)

### CODE REVIEW

**Review by honzatmn — CHANGES_REQUESTED** [review]
Hi Kellie, thanks for your first contribution! Can you please check all the changes? It changes the formatting of the document and added a lot of whitespace – it may be because of some settings in your IDE.

**Comment by kelliedesigner** [comment]
I've checked this is Markdown preview and it looks fine, I just removed the one row, I know that it's showing up with loads of green and read in files changed but I can't see any issue or extra white space in preview.

**Comment by honzatmn** [comment]
@kelliedesigner It looks like your IDE is adding some unnecessary spaces/tabs when using some Markdown preview feature. I can't merge it without cleaning the code – only change should be removed role, nothing else changed.

**Comment by kelliedesigner** [comment]
Closing as failed to rebase.

**Pull request closed without merging**
